<a href="<?php echo $this->url(array(), "index", true); ?>"
   class="no-bottom"><i class="icon-home"></i> Início</a>&nbsp;&nbsp;
<a href="<?php echo $this->url(array(), 'login', true) ?>"
   class="no-bottom"><i class="icon-signin"></i> Entrar</a>

<h2>Cadastro</h2>
<div><font color="red"><b>ATENÇÃO:</b></font> <font color="#828282">utilize uma conta de e-mail que <b>NÃO</b> seja Hotmail, Outlook ou Live.</font></div>
<div><font color="#828282">* Campos obrigatórios</font></div>
<hr/>

<?php
echo $this->form;
