<a href="<?php echo $this->url(array(), "index", true); ?>"
   class="no-bottom"><i class="icon-home"></i> Início</a>

<h2>Autenticação</h2>
<hr/>
<?php
echo $this->form;
?>

<a href="<?php echo $this->url(array(), 'recuperar-senha', true); ?>"
   class="no-bottom"><i class="icon-key"></i> Esqueci Minha Senha</a> 
<br>
<a href="<?php echo $this->url(array(), 'participar', true); ?>"
   class="no-bottom"><i class="icon-hand-right"></i> Participe Agora</a>