<div>
    <img class="fl_left"  src="<?php echo $this->baseUrl('imagens/layout/icn_sige.png') ?>"></img>

    <p  class="fl_left cl_right" align="center"> 
        SIGE por <a href="http://comsolid.org" target="_blank" style="color: white">COMSOLiD</a> - <?php echo date('Y') ?> |
        <a href="<?php echo $this->url(array(), 'sobre', true) ?>" style="color: white">Sobre</a> | 
        <a href="<?php echo $this->url(array(), 'ajuda', true) ?>" style="color: white">Ajuda</a>
    </p>
    <a href="http://sic.maracanau.ifce.edu.br" target="_blank">
        <img class="fl_center fl_center" src="<?php echo $this->baseUrl('imagens/layout/icn_sic.png') ?>" alt="SIC" border="0"/>
    </a>
   	
        <img class="fl_right cl_right" src="<?php echo $this->baseUrl('imagens/layout/icn_comsolid.png') ?>" alt="COMSOLiD" border="0" height="53" width="180"/>
   
</div>
