<?php
$this->headLink()->appendStylesheet($this->baseUrl('css/jqueryui-bootstrap/jquery.ui.1.8.16.ie.css'));
$this->headLink()->appendStylesheet($this->baseUrl('css/jqueryui-bootstrap/jquery-ui-1.8.16.custom.css'));
$this->headLink()->appendStylesheet($this->baseUrl('css/screen.css'));
$this->headLink()->appendStylesheet($this->baseUrl('css/form.css'));
$this->headLink()->appendStylesheet($this->baseUrl('lib/select2/select2.css'));
$this->headLink()->appendStylesheet($this->baseUrl('css/iphone-style-checkbox.css'));

$this->headScript()->appendFile($this->baseUrl('js/jquery-1.11.3.min.js'));
$this->headScript()->appendFile($this->baseUrl('js/jquery-ui-1.8.16.custom.min.js'), 'text/javascript');
$this->headScript()->appendFile($this->baseUrl('lib/select2/select2.min.js'));
$this->headScript()->appendFile($this->baseUrl('js/iphone-style-checkboxes.js'));
$this->headScript()->appendFile($this->baseUrl('js/admin/encontro/salvar.js'), 'text/javascript');
?>

<h3>Editar Encontro</h3><hr/>
<?php
echo $this->form;
