/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-11-01 10:41:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.components.bam.displayer.domain;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.jboss.dashboard.domain.date.DateDomain;
import java.text.SimpleDateFormat;
import org.jboss.dashboard.LocaleManager;
import java.util.ResourceBundle;
import org.jboss.dashboard.domain.DomainConfiguration;
import org.jboss.dashboard.domain.AbstractDomain;

public final class date_005fdomain_005fdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fi18n_005fbundle_0026_005flocale_005fid_005fbaseName_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fi18n_005fmessage_0026_005fkey;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffactory_005fencode_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fstatic_005fimage_0026_005frelativePath_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fi18n_005fbundle_0026_005flocale_005fid_005fbaseName_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fi18n_005fmessage_0026_005fkey = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffactory_005fencode_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fstatic_005fimage_0026_005frelativePath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fi18n_005fbundle_0026_005flocale_005fid_005fbaseName_005fnobody.release();
    _005fjspx_005ftagPool_005fi18n_005fmessage_0026_005fkey.release();
    _005fjspx_005ftagPool_005ffactory_005fencode_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fstatic_005fimage_0026_005frelativePath_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      //  i18n:bundle
      java.util.ResourceBundle bundle = null;
      org.jboss.dashboard.ui.taglib.BundleTag _jspx_th_i18n_005fbundle_005f0 = (org.jboss.dashboard.ui.taglib.BundleTag) _005fjspx_005ftagPool_005fi18n_005fbundle_0026_005flocale_005fid_005fbaseName_005fnobody.get(org.jboss.dashboard.ui.taglib.BundleTag.class);
      boolean _jspx_th_i18n_005fbundle_005f0_reused = false;
      try {
        _jspx_th_i18n_005fbundle_005f0.setPageContext(_jspx_page_context);
        _jspx_th_i18n_005fbundle_005f0.setParent(null);
        // /components/bam/displayer/domain/date_domain_details.jsp(30,0) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_i18n_005fbundle_005f0.setId("bundle");
        // /components/bam/displayer/domain/date_domain_details.jsp(30,0) name = baseName type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_i18n_005fbundle_005f0.setBaseName("org.jboss.dashboard.displayer.messages");
        // /components/bam/displayer/domain/date_domain_details.jsp(30,0) name = locale type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_i18n_005fbundle_005f0.setLocale(LocaleManager.currentLocale());
        int _jspx_eval_i18n_005fbundle_005f0 = _jspx_th_i18n_005fbundle_005f0.doStartTag();
        if (_jspx_th_i18n_005fbundle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        bundle = (java.util.ResourceBundle) _jspx_page_context.findAttribute("bundle");
        _005fjspx_005ftagPool_005fi18n_005fbundle_0026_005flocale_005fid_005fbaseName_005fnobody.reuse(_jspx_th_i18n_005fbundle_005f0);
        _jspx_th_i18n_005fbundle_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_i18n_005fbundle_005f0, _jsp_getInstanceManager(), _jspx_th_i18n_005fbundle_005f0_reused);
      }
      out.write('\n');

    DomainConfiguration domainConfig =  (DomainConfiguration) request.getAttribute("domainConfig");

      out.write("\n");
      out.write("    <tr>\n");
      out.write("        <td width=\"160px\" height=\"15\" nowrap=\"nowrap\" align=\"left\" class=\"skn-even_row\">\n");
      out.write("                ");
      //  i18n:message
      org.jboss.dashboard.ui.taglib.MessageTag _jspx_th_i18n_005fmessage_005f0 = (org.jboss.dashboard.ui.taglib.MessageTag) _005fjspx_005ftagPool_005fi18n_005fmessage_0026_005fkey.get(org.jboss.dashboard.ui.taglib.MessageTag.class);
      boolean _jspx_th_i18n_005fmessage_005f0_reused = false;
      try {
        _jspx_th_i18n_005fmessage_005f0.setPageContext(_jspx_page_context);
        _jspx_th_i18n_005fmessage_005f0.setParent(null);
        // /components/bam/displayer/domain/date_domain_details.jsp(36,16) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_i18n_005fmessage_005f0.setKey( DateDomain.I18N_PREFFIX + "dateTamInterval");
        int _jspx_eval_i18n_005fmessage_005f0 = _jspx_th_i18n_005fmessage_005f0.doStartTag();
        if (_jspx_eval_i18n_005fmessage_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_i18n_005fmessage_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_i18n_005fmessage_005f0);
          }
          do {
            out.write("!!Tamano del intervalo");
            int evalDoAfterBody = _jspx_th_i18n_005fmessage_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_i18n_005fmessage_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_i18n_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fi18n_005fmessage_0026_005fkey.reuse(_jspx_th_i18n_005fmessage_005f0);
        _jspx_th_i18n_005fmessage_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_i18n_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_i18n_005fmessage_005f0_reused);
      }
      out.write(":\n");
      out.write("        </td>\n");
      out.write("        <td nowrap=\"nowrap\" align=\"left\">\n");
      out.write("            <select name=\"dateTamInterval\" class=\"skn-input\" style=\"width:120px;\">\n");
      out.write("            ");

                String tamPredefinido = "";
                if (domainConfig.getDateTamInterval().equals("-1") ) tamPredefinido = "selected";
            
      out.write("\n");
      out.write("                 <option value=\"-1\" ");
      out.print( tamPredefinido );
      out.write(">\n");
      out.write("                    ");
      //  i18n:message
      org.jboss.dashboard.ui.taglib.MessageTag _jspx_th_i18n_005fmessage_005f1 = (org.jboss.dashboard.ui.taglib.MessageTag) _005fjspx_005ftagPool_005fi18n_005fmessage_0026_005fkey.get(org.jboss.dashboard.ui.taglib.MessageTag.class);
      boolean _jspx_th_i18n_005fmessage_005f1_reused = false;
      try {
        _jspx_th_i18n_005fmessage_005f1.setPageContext(_jspx_page_context);
        _jspx_th_i18n_005fmessage_005f1.setParent(null);
        // /components/bam/displayer/domain/date_domain_details.jsp(45,20) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_i18n_005fmessage_005f1.setKey( AbstractDomain.I18N_PREFFIX + "tamPredefined");
        int _jspx_eval_i18n_005fmessage_005f1 = _jspx_th_i18n_005fmessage_005f1.doStartTag();
        if (_jspx_eval_i18n_005fmessage_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_i18n_005fmessage_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_i18n_005fmessage_005f1);
          }
          do {
            out.write("!!!TamaÃ±o predefinido");
            int evalDoAfterBody = _jspx_th_i18n_005fmessage_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_i18n_005fmessage_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_i18n_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fi18n_005fmessage_0026_005fkey.reuse(_jspx_th_i18n_005fmessage_005f1);
        _jspx_th_i18n_005fmessage_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_i18n_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_i18n_005fmessage_005f1_reused);
      }
      out.write("\n");
      out.write("                </option>\n");
      out.write("            ");

                // i18n
                ResourceBundle i18n = LocaleManager.lookup().getBundle("org.jboss.dashboard.displayer.messages", LocaleManager.currentLocale());
                String[] dateIntervals = new String[] {
                        i18n.getString(DateDomain.I18N_PREFFIX + "seconds"),
                        i18n.getString(DateDomain.I18N_PREFFIX + "minutes"),
                        i18n.getString(DateDomain.I18N_PREFFIX + "hours"),
                        i18n.getString(DateDomain.I18N_PREFFIX + "days"),
                        i18n.getString(DateDomain.I18N_PREFFIX + "weeks"),
                        i18n.getString(DateDomain.I18N_PREFFIX + "months"),
                        i18n.getString(DateDomain.I18N_PREFFIX + "quarters"),
                        i18n.getString(DateDomain.I18N_PREFFIX + "years"),
                        i18n.getString(DateDomain.I18N_PREFFIX + "decades")};
                for (int i = 0; i < dateIntervals.length; i++) {
                    String selected = "";
                    if (i == Integer.parseInt(domainConfig.getDateTamInterval())) selected = "selected";
            
      out.write("\n");
      out.write("                    <option value=\"");
      out.print( i );
      out.write('"');
      out.write(' ');
      out.print( selected );
      out.write(">\n");
      out.write("                        ");
      out.print( dateIntervals[i] );
      out.write("\n");
      out.write("                    </option>\n");
      out.write("            ");

                }
            
      out.write("\n");
      out.write("            </select>\n");
      out.write("        </td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("        <td height=\"15\" nowrap=\"nowrap\" align=\"left\" class=\"skn-even_row\">\n");
      out.write("                ");
      //  i18n:message
      org.jboss.dashboard.ui.taglib.MessageTag _jspx_th_i18n_005fmessage_005f2 = (org.jboss.dashboard.ui.taglib.MessageTag) _005fjspx_005ftagPool_005fi18n_005fmessage_0026_005fkey.get(org.jboss.dashboard.ui.taglib.MessageTag.class);
      boolean _jspx_th_i18n_005fmessage_005f2_reused = false;
      try {
        _jspx_th_i18n_005fmessage_005f2.setPageContext(_jspx_page_context);
        _jspx_th_i18n_005fmessage_005f2.setParent(null);
        // /components/bam/displayer/domain/date_domain_details.jsp(75,16) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_i18n_005fmessage_005f2.setKey( DateDomain.I18N_PREFFIX + "initialDate");
        int _jspx_eval_i18n_005fmessage_005f2 = _jspx_th_i18n_005fmessage_005f2.doStartTag();
        if (_jspx_eval_i18n_005fmessage_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_i18n_005fmessage_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_i18n_005fmessage_005f2);
          }
          do {
            out.write("!!Fecha de inicio");
            int evalDoAfterBody = _jspx_th_i18n_005fmessage_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_i18n_005fmessage_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_i18n_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fi18n_005fmessage_0026_005fkey.reuse(_jspx_th_i18n_005fmessage_005f2);
        _jspx_th_i18n_005fmessage_005f2_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_i18n_005fmessage_005f2, _jsp_getInstanceManager(), _jspx_th_i18n_005fmessage_005f2_reused);
      }
      out.write(":\n");
      out.write("        </td>\n");
      out.write("        <td nowrap=\"nowrap\" align=\"left\">\n");
      out.write("            ");
 String minDate = domainConfig.getDateMinDate(); 
      out.write("\n");
      out.write("            <input class=\"skn-input\" name=\"initialDate\" id=\"");
      if (_jspx_meth_factory_005fencode_005f0(_jspx_page_context))
        return;
      out.write("\" type=\"text\" value=\"");
      out.print( minDate == null || minDate.trim().equals("") ? "" : minDate );
      out.write("\">&nbsp;\n");
      out.write("            <a href=\"#\" onclick=\"NewCal('");
      if (_jspx_meth_factory_005fencode_005f1(_jspx_page_context))
        return;
      out.write("','ddmmyyyy',true,24); return false;\">\n");
      out.write("                <img src=\"");
      if (_jspx_meth_static_005fimage_005f0(_jspx_page_context))
        return;
      out.write("\" border=\"0\"></a>&nbsp;\n");
      out.write("            <a href=\"#\">\n");
      out.write("                <img src=\"");
      if (_jspx_meth_static_005fimage_005f1(_jspx_page_context))
        return;
      out.write("\" border=\"0\"\n");
      out.write("                     onclick=\"document.getElementById('");
      if (_jspx_meth_factory_005fencode_005f2(_jspx_page_context))
        return;
      out.write("').value=''; return false;\"></a>\n");
      out.write("        </td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("        <td height=\"15\" nowrap=\"nowrap\" align=\"left\" class=\"skn-even_row\">\n");
      out.write("                ");
      //  i18n:message
      org.jboss.dashboard.ui.taglib.MessageTag _jspx_th_i18n_005fmessage_005f3 = (org.jboss.dashboard.ui.taglib.MessageTag) _005fjspx_005ftagPool_005fi18n_005fmessage_0026_005fkey.get(org.jboss.dashboard.ui.taglib.MessageTag.class);
      boolean _jspx_th_i18n_005fmessage_005f3_reused = false;
      try {
        _jspx_th_i18n_005fmessage_005f3.setPageContext(_jspx_page_context);
        _jspx_th_i18n_005fmessage_005f3.setParent(null);
        // /components/bam/displayer/domain/date_domain_details.jsp(89,16) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_i18n_005fmessage_005f3.setKey( DateDomain.I18N_PREFFIX + "endDate");
        int _jspx_eval_i18n_005fmessage_005f3 = _jspx_th_i18n_005fmessage_005f3.doStartTag();
        if (_jspx_eval_i18n_005fmessage_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_i18n_005fmessage_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_i18n_005fmessage_005f3);
          }
          do {
            out.write("!!Fecha de fin");
            int evalDoAfterBody = _jspx_th_i18n_005fmessage_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_i18n_005fmessage_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_i18n_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fi18n_005fmessage_0026_005fkey.reuse(_jspx_th_i18n_005fmessage_005f3);
        _jspx_th_i18n_005fmessage_005f3_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_i18n_005fmessage_005f3, _jsp_getInstanceManager(), _jspx_th_i18n_005fmessage_005f3_reused);
      }
      out.write(":\n");
      out.write("        </td>\n");
      out.write("        <td nowrap=\"nowrap\" align=\"left\">\n");
      out.write("            ");
 String maxDate = domainConfig.getDateMaxDate(); 
      out.write("\n");
      out.write("            <input class=\"skn-input\" name=\"endDate\" id=\"");
      if (_jspx_meth_factory_005fencode_005f3(_jspx_page_context))
        return;
      out.write("\" type=\"text\" value=\"");
      out.print( maxDate == null || maxDate.trim().equals("") ? "" : maxDate );
      out.write("\">&nbsp;\n");
      out.write("            <a href=\"#\" onclick=\"NewCal('");
      if (_jspx_meth_factory_005fencode_005f4(_jspx_page_context))
        return;
      out.write("','ddmmyyyy',true,24); return false;\">\n");
      out.write("                <img src=\"");
      if (_jspx_meth_static_005fimage_005f2(_jspx_page_context))
        return;
      out.write("\" border=\"0\"></a>&nbsp;\n");
      out.write("            <a href=\"#\">\n");
      out.write("                <img src=\"");
      if (_jspx_meth_static_005fimage_005f3(_jspx_page_context))
        return;
      out.write("\" border=\"0\"\n");
      out.write("                     onclick=\"document.getElementById('");
      if (_jspx_meth_factory_005fencode_005f5(_jspx_page_context))
        return;
      out.write("').value=''; return false;\"></a>\n");
      out.write("        </td>\n");
      out.write("    </tr>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_factory_005fencode_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  factory:encode
    org.jboss.dashboard.ui.taglib.factory.EncodeTag _jspx_th_factory_005fencode_005f0 = (org.jboss.dashboard.ui.taglib.factory.EncodeTag) _005fjspx_005ftagPool_005ffactory_005fencode_0026_005fname_005fnobody.get(org.jboss.dashboard.ui.taglib.factory.EncodeTag.class);
    boolean _jspx_th_factory_005fencode_005f0_reused = false;
    try {
      _jspx_th_factory_005fencode_005f0.setPageContext(_jspx_page_context);
      _jspx_th_factory_005fencode_005f0.setParent(null);
      // /components/bam/displayer/domain/date_domain_details.jsp(79,60) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_factory_005fencode_005f0.setName("initialDate");
      int _jspx_eval_factory_005fencode_005f0 = _jspx_th_factory_005fencode_005f0.doStartTag();
      if (_jspx_th_factory_005fencode_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffactory_005fencode_0026_005fname_005fnobody.reuse(_jspx_th_factory_005fencode_005f0);
      _jspx_th_factory_005fencode_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_factory_005fencode_005f0, _jsp_getInstanceManager(), _jspx_th_factory_005fencode_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_factory_005fencode_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  factory:encode
    org.jboss.dashboard.ui.taglib.factory.EncodeTag _jspx_th_factory_005fencode_005f1 = (org.jboss.dashboard.ui.taglib.factory.EncodeTag) _005fjspx_005ftagPool_005ffactory_005fencode_0026_005fname_005fnobody.get(org.jboss.dashboard.ui.taglib.factory.EncodeTag.class);
    boolean _jspx_th_factory_005fencode_005f1_reused = false;
    try {
      _jspx_th_factory_005fencode_005f1.setPageContext(_jspx_page_context);
      _jspx_th_factory_005fencode_005f1.setParent(null);
      // /components/bam/displayer/domain/date_domain_details.jsp(80,41) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_factory_005fencode_005f1.setName("initialDate");
      int _jspx_eval_factory_005fencode_005f1 = _jspx_th_factory_005fencode_005f1.doStartTag();
      if (_jspx_th_factory_005fencode_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffactory_005fencode_0026_005fname_005fnobody.reuse(_jspx_th_factory_005fencode_005f1);
      _jspx_th_factory_005fencode_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_factory_005fencode_005f1, _jsp_getInstanceManager(), _jspx_th_factory_005fencode_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_static_005fimage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  static:image
    org.jboss.dashboard.ui.taglib.resource.ImageResolverTag _jspx_th_static_005fimage_005f0 = (org.jboss.dashboard.ui.taglib.resource.ImageResolverTag) _005fjspx_005ftagPool_005fstatic_005fimage_0026_005frelativePath_005fnobody.get(org.jboss.dashboard.ui.taglib.resource.ImageResolverTag.class);
    boolean _jspx_th_static_005fimage_005f0_reused = false;
    try {
      _jspx_th_static_005fimage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_static_005fimage_005f0.setParent(null);
      // /components/bam/displayer/domain/date_domain_details.jsp(81,26) name = relativePath type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_static_005fimage_005f0.setRelativePath("general/16x16/ico-calendar.png");
      int _jspx_eval_static_005fimage_005f0 = _jspx_th_static_005fimage_005f0.doStartTag();
      if (_jspx_th_static_005fimage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fstatic_005fimage_0026_005frelativePath_005fnobody.reuse(_jspx_th_static_005fimage_005f0);
      _jspx_th_static_005fimage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_static_005fimage_005f0, _jsp_getInstanceManager(), _jspx_th_static_005fimage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_static_005fimage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  static:image
    org.jboss.dashboard.ui.taglib.resource.ImageResolverTag _jspx_th_static_005fimage_005f1 = (org.jboss.dashboard.ui.taglib.resource.ImageResolverTag) _005fjspx_005ftagPool_005fstatic_005fimage_0026_005frelativePath_005fnobody.get(org.jboss.dashboard.ui.taglib.resource.ImageResolverTag.class);
    boolean _jspx_th_static_005fimage_005f1_reused = false;
    try {
      _jspx_th_static_005fimage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_static_005fimage_005f1.setParent(null);
      // /components/bam/displayer/domain/date_domain_details.jsp(83,26) name = relativePath type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_static_005fimage_005f1.setRelativePath("general/16x16/ico-trash.png");
      int _jspx_eval_static_005fimage_005f1 = _jspx_th_static_005fimage_005f1.doStartTag();
      if (_jspx_th_static_005fimage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fstatic_005fimage_0026_005frelativePath_005fnobody.reuse(_jspx_th_static_005fimage_005f1);
      _jspx_th_static_005fimage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_static_005fimage_005f1, _jsp_getInstanceManager(), _jspx_th_static_005fimage_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_factory_005fencode_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  factory:encode
    org.jboss.dashboard.ui.taglib.factory.EncodeTag _jspx_th_factory_005fencode_005f2 = (org.jboss.dashboard.ui.taglib.factory.EncodeTag) _005fjspx_005ftagPool_005ffactory_005fencode_0026_005fname_005fnobody.get(org.jboss.dashboard.ui.taglib.factory.EncodeTag.class);
    boolean _jspx_th_factory_005fencode_005f2_reused = false;
    try {
      _jspx_th_factory_005fencode_005f2.setPageContext(_jspx_page_context);
      _jspx_th_factory_005fencode_005f2.setParent(null);
      // /components/bam/displayer/domain/date_domain_details.jsp(84,55) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_factory_005fencode_005f2.setName("initialDate");
      int _jspx_eval_factory_005fencode_005f2 = _jspx_th_factory_005fencode_005f2.doStartTag();
      if (_jspx_th_factory_005fencode_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffactory_005fencode_0026_005fname_005fnobody.reuse(_jspx_th_factory_005fencode_005f2);
      _jspx_th_factory_005fencode_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_factory_005fencode_005f2, _jsp_getInstanceManager(), _jspx_th_factory_005fencode_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_factory_005fencode_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  factory:encode
    org.jboss.dashboard.ui.taglib.factory.EncodeTag _jspx_th_factory_005fencode_005f3 = (org.jboss.dashboard.ui.taglib.factory.EncodeTag) _005fjspx_005ftagPool_005ffactory_005fencode_0026_005fname_005fnobody.get(org.jboss.dashboard.ui.taglib.factory.EncodeTag.class);
    boolean _jspx_th_factory_005fencode_005f3_reused = false;
    try {
      _jspx_th_factory_005fencode_005f3.setPageContext(_jspx_page_context);
      _jspx_th_factory_005fencode_005f3.setParent(null);
      // /components/bam/displayer/domain/date_domain_details.jsp(93,56) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_factory_005fencode_005f3.setName("endDate");
      int _jspx_eval_factory_005fencode_005f3 = _jspx_th_factory_005fencode_005f3.doStartTag();
      if (_jspx_th_factory_005fencode_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffactory_005fencode_0026_005fname_005fnobody.reuse(_jspx_th_factory_005fencode_005f3);
      _jspx_th_factory_005fencode_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_factory_005fencode_005f3, _jsp_getInstanceManager(), _jspx_th_factory_005fencode_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_factory_005fencode_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  factory:encode
    org.jboss.dashboard.ui.taglib.factory.EncodeTag _jspx_th_factory_005fencode_005f4 = (org.jboss.dashboard.ui.taglib.factory.EncodeTag) _005fjspx_005ftagPool_005ffactory_005fencode_0026_005fname_005fnobody.get(org.jboss.dashboard.ui.taglib.factory.EncodeTag.class);
    boolean _jspx_th_factory_005fencode_005f4_reused = false;
    try {
      _jspx_th_factory_005fencode_005f4.setPageContext(_jspx_page_context);
      _jspx_th_factory_005fencode_005f4.setParent(null);
      // /components/bam/displayer/domain/date_domain_details.jsp(94,41) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_factory_005fencode_005f4.setName("endDate");
      int _jspx_eval_factory_005fencode_005f4 = _jspx_th_factory_005fencode_005f4.doStartTag();
      if (_jspx_th_factory_005fencode_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffactory_005fencode_0026_005fname_005fnobody.reuse(_jspx_th_factory_005fencode_005f4);
      _jspx_th_factory_005fencode_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_factory_005fencode_005f4, _jsp_getInstanceManager(), _jspx_th_factory_005fencode_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_static_005fimage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  static:image
    org.jboss.dashboard.ui.taglib.resource.ImageResolverTag _jspx_th_static_005fimage_005f2 = (org.jboss.dashboard.ui.taglib.resource.ImageResolverTag) _005fjspx_005ftagPool_005fstatic_005fimage_0026_005frelativePath_005fnobody.get(org.jboss.dashboard.ui.taglib.resource.ImageResolverTag.class);
    boolean _jspx_th_static_005fimage_005f2_reused = false;
    try {
      _jspx_th_static_005fimage_005f2.setPageContext(_jspx_page_context);
      _jspx_th_static_005fimage_005f2.setParent(null);
      // /components/bam/displayer/domain/date_domain_details.jsp(95,26) name = relativePath type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_static_005fimage_005f2.setRelativePath("general/16x16/ico-calendar.png");
      int _jspx_eval_static_005fimage_005f2 = _jspx_th_static_005fimage_005f2.doStartTag();
      if (_jspx_th_static_005fimage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fstatic_005fimage_0026_005frelativePath_005fnobody.reuse(_jspx_th_static_005fimage_005f2);
      _jspx_th_static_005fimage_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_static_005fimage_005f2, _jsp_getInstanceManager(), _jspx_th_static_005fimage_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_static_005fimage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  static:image
    org.jboss.dashboard.ui.taglib.resource.ImageResolverTag _jspx_th_static_005fimage_005f3 = (org.jboss.dashboard.ui.taglib.resource.ImageResolverTag) _005fjspx_005ftagPool_005fstatic_005fimage_0026_005frelativePath_005fnobody.get(org.jboss.dashboard.ui.taglib.resource.ImageResolverTag.class);
    boolean _jspx_th_static_005fimage_005f3_reused = false;
    try {
      _jspx_th_static_005fimage_005f3.setPageContext(_jspx_page_context);
      _jspx_th_static_005fimage_005f3.setParent(null);
      // /components/bam/displayer/domain/date_domain_details.jsp(97,26) name = relativePath type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_static_005fimage_005f3.setRelativePath("general/16x16/ico-trash.png");
      int _jspx_eval_static_005fimage_005f3 = _jspx_th_static_005fimage_005f3.doStartTag();
      if (_jspx_th_static_005fimage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fstatic_005fimage_0026_005frelativePath_005fnobody.reuse(_jspx_th_static_005fimage_005f3);
      _jspx_th_static_005fimage_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_static_005fimage_005f3, _jsp_getInstanceManager(), _jspx_th_static_005fimage_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_factory_005fencode_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  factory:encode
    org.jboss.dashboard.ui.taglib.factory.EncodeTag _jspx_th_factory_005fencode_005f5 = (org.jboss.dashboard.ui.taglib.factory.EncodeTag) _005fjspx_005ftagPool_005ffactory_005fencode_0026_005fname_005fnobody.get(org.jboss.dashboard.ui.taglib.factory.EncodeTag.class);
    boolean _jspx_th_factory_005fencode_005f5_reused = false;
    try {
      _jspx_th_factory_005fencode_005f5.setPageContext(_jspx_page_context);
      _jspx_th_factory_005fencode_005f5.setParent(null);
      // /components/bam/displayer/domain/date_domain_details.jsp(98,55) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_factory_005fencode_005f5.setName("endDate");
      int _jspx_eval_factory_005fencode_005f5 = _jspx_th_factory_005fencode_005f5.doStartTag();
      if (_jspx_th_factory_005fencode_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffactory_005fencode_0026_005fname_005fnobody.reuse(_jspx_th_factory_005fencode_005f5);
      _jspx_th_factory_005fencode_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_factory_005fencode_005f5, _jsp_getInstanceManager(), _jspx_th_factory_005fencode_005f5_reused);
    }
    return false;
  }
}
