/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-10-09 00:12:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.envelopes.Envelope_005fIFCE;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.jboss.dashboard.ui.SessionManager;
import org.jboss.dashboard.workspace.*;
import org.jboss.dashboard.security.WorkspacePermission;
import java.security.AllPermission;
import java.security.Permission;
import java.util.Locale;
import org.jboss.dashboard.LocaleManager;
import org.jboss.dashboard.ui.NavigationManager;
import org.jboss.dashboard.Application;

public final class full_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/global.jsp", Long.valueOf(1460669778000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fi18n_005fbundle_0026_005flocale_005fid_005fbaseName_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffactory_005fproperty_0026_005fproperty_005fbean_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpanel_005fenvelopeHead_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpanel_005fpropertyRead_0026_005fproperty_005fobject_005flocalize_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fmvc_005fpane_0026_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpanel_005fenvelopeFooter_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fi18n_005fbundle_0026_005flocale_005fid_005fbaseName_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffactory_005fproperty_0026_005fproperty_005fbean_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpanel_005fenvelopeHead_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpanel_005fpropertyRead_0026_005fproperty_005fobject_005flocalize_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fmvc_005fpane_0026_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpanel_005fenvelopeFooter_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fi18n_005fbundle_0026_005flocale_005fid_005fbaseName_005fnobody.release();
    _005fjspx_005ftagPool_005ffactory_005fproperty_0026_005fproperty_005fbean_005fnobody.release();
    _005fjspx_005ftagPool_005fpanel_005fenvelopeHead_005fnobody.release();
    _005fjspx_005ftagPool_005fpanel_005fpropertyRead_0026_005fproperty_005fobject_005flocalize_005fnobody.release();
    _005fjspx_005ftagPool_005fmvc_005fpane_0026_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005fpanel_005fenvelopeFooter_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    LocaleManager localeManager = LocaleManager.lookup();
    NavigationManager navigationManager = NavigationManager.lookup();
    Section currentSection = navigationManager.getCurrentSection();
    Workspace currentWorkspace = navigationManager.getCurrentWorkspace();
    Locale currentLocale = localeManager.getCurrentLocale();
    boolean adminMode = navigationManager.userIsAdminInCurrentWorkspace();

      out.write('\n');
      //  i18n:bundle
      java.util.ResourceBundle bundle = null;
      org.jboss.dashboard.ui.taglib.BundleTag _jspx_th_i18n_005fbundle_005f0 = (org.jboss.dashboard.ui.taglib.BundleTag) _005fjspx_005ftagPool_005fi18n_005fbundle_0026_005flocale_005fid_005fbaseName_005fnobody.get(org.jboss.dashboard.ui.taglib.BundleTag.class);
      boolean _jspx_th_i18n_005fbundle_005f0_reused = false;
      try {
        _jspx_th_i18n_005fbundle_005f0.setPageContext(_jspx_page_context);
        _jspx_th_i18n_005fbundle_005f0.setParent(null);
        // /common/global.jsp(39,0) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_i18n_005fbundle_005f0.setId("bundle");
        // /common/global.jsp(39,0) name = baseName type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_i18n_005fbundle_005f0.setBaseName("org.jboss.dashboard.ui.messages");
        // /common/global.jsp(39,0) name = locale type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_i18n_005fbundle_005f0.setLocale(localeManager.getCurrentLocale());
        int _jspx_eval_i18n_005fbundle_005f0 = _jspx_th_i18n_005fbundle_005f0.doStartTag();
        if (_jspx_th_i18n_005fbundle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        bundle = (java.util.ResourceBundle) _jspx_page_context.findAttribute("bundle");
        _005fjspx_005ftagPool_005fi18n_005fbundle_0026_005flocale_005fid_005fbaseName_005fnobody.reuse(_jspx_th_i18n_005fbundle_005f0);
        _jspx_th_i18n_005fbundle_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_i18n_005fbundle_005f0, _jsp_getInstanceManager(), _jspx_th_i18n_005fbundle_005f0_reused);
      }
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"");
      //  factory:property
      org.jboss.dashboard.ui.taglib.factory.PropertyTag _jspx_th_factory_005fproperty_005f0 = (org.jboss.dashboard.ui.taglib.factory.PropertyTag) _005fjspx_005ftagPool_005ffactory_005fproperty_0026_005fproperty_005fbean_005fnobody.get(org.jboss.dashboard.ui.taglib.factory.PropertyTag.class);
      boolean _jspx_th_factory_005fproperty_005f0_reused = false;
      try {
        _jspx_th_factory_005fproperty_005f0.setPageContext(_jspx_page_context);
        _jspx_th_factory_005fproperty_005f0.setParent(null);
        // /envelopes/Envelope_IFCE/full.jsp(22,12) name = bean type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_factory_005fproperty_005f0.setBean("org.jboss.dashboard.LocaleManager");
        // /envelopes/Envelope_IFCE/full.jsp(22,12) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_factory_005fproperty_005f0.setProperty("currentLang");
        int _jspx_eval_factory_005fproperty_005f0 = _jspx_th_factory_005fproperty_005f0.doStartTag();
        if (_jspx_th_factory_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffactory_005fproperty_0026_005fproperty_005fbean_005fnobody.reuse(_jspx_th_factory_005fproperty_005f0);
        _jspx_th_factory_005fproperty_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_factory_005fproperty_005f0, _jsp_getInstanceManager(), _jspx_th_factory_005fproperty_005f0_reused);
      }
      out.write("\">\n");
      out.write("<head>\n");
      out.write("    ");
      if (_jspx_meth_panel_005fenvelopeHead_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    <title>");
      if (_jspx_meth_panel_005fpropertyRead_005f0(_jspx_page_context))
        return;
      out.write(' ');
      out.write('-');
      out.write(' ');
      if (_jspx_meth_panel_005fpropertyRead_005f1(_jspx_page_context))
        return;
      out.write("</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body style=\"background:white;\">\n");
      out.write("\n");
      out.write("<table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("\n");
      out.write("    <tr>\n");
      out.write("        <td valign=\"top\" align=\"center\">");
      if (_jspx_meth_mvc_005fpane_005f0(_jspx_page_context))
        return;
      out.write("</td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("      <td valign=\"top\" align=\"center\">&nbsp;</td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("      <td valign=\"top\" align=\"center\"><br>");
      out.print( Application.lookup().getCopyright() );
      out.write("</td>\n");
      out.write("    </tr>\n");
      out.write("</table>\n");
      if (_jspx_meth_panel_005fenvelopeFooter_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_panel_005fenvelopeHead_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  panel:envelopeHead
    org.jboss.dashboard.ui.taglib.EnvelopeHeadTag _jspx_th_panel_005fenvelopeHead_005f0 = (org.jboss.dashboard.ui.taglib.EnvelopeHeadTag) _005fjspx_005ftagPool_005fpanel_005fenvelopeHead_005fnobody.get(org.jboss.dashboard.ui.taglib.EnvelopeHeadTag.class);
    boolean _jspx_th_panel_005fenvelopeHead_005f0_reused = false;
    try {
      _jspx_th_panel_005fenvelopeHead_005f0.setPageContext(_jspx_page_context);
      _jspx_th_panel_005fenvelopeHead_005f0.setParent(null);
      int _jspx_eval_panel_005fenvelopeHead_005f0 = _jspx_th_panel_005fenvelopeHead_005f0.doStartTag();
      if (_jspx_th_panel_005fenvelopeHead_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpanel_005fenvelopeHead_005fnobody.reuse(_jspx_th_panel_005fenvelopeHead_005f0);
      _jspx_th_panel_005fenvelopeHead_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_panel_005fenvelopeHead_005f0, _jsp_getInstanceManager(), _jspx_th_panel_005fenvelopeHead_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_panel_005fpropertyRead_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  panel:propertyRead
    org.jboss.dashboard.ui.taglib.PropertyReadTag _jspx_th_panel_005fpropertyRead_005f0 = (org.jboss.dashboard.ui.taglib.PropertyReadTag) _005fjspx_005ftagPool_005fpanel_005fpropertyRead_0026_005fproperty_005fobject_005flocalize_005fnobody.get(org.jboss.dashboard.ui.taglib.PropertyReadTag.class);
    boolean _jspx_th_panel_005fpropertyRead_005f0_reused = false;
    try {
      _jspx_th_panel_005fpropertyRead_005f0.setPageContext(_jspx_page_context);
      _jspx_th_panel_005fpropertyRead_005f0.setParent(null);
      // /envelopes/Envelope_IFCE/full.jsp(25,11) name = localize type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_panel_005fpropertyRead_005f0.setLocalize(new java.lang.Boolean(true));
      // /envelopes/Envelope_IFCE/full.jsp(25,11) name = object type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_panel_005fpropertyRead_005f0.setObject("workspace");
      // /envelopes/Envelope_IFCE/full.jsp(25,11) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_panel_005fpropertyRead_005f0.setProperty("title");
      int _jspx_eval_panel_005fpropertyRead_005f0 = _jspx_th_panel_005fpropertyRead_005f0.doStartTag();
      if (_jspx_th_panel_005fpropertyRead_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpanel_005fpropertyRead_0026_005fproperty_005fobject_005flocalize_005fnobody.reuse(_jspx_th_panel_005fpropertyRead_005f0);
      _jspx_th_panel_005fpropertyRead_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_panel_005fpropertyRead_005f0, _jsp_getInstanceManager(), _jspx_th_panel_005fpropertyRead_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_panel_005fpropertyRead_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  panel:propertyRead
    org.jboss.dashboard.ui.taglib.PropertyReadTag _jspx_th_panel_005fpropertyRead_005f1 = (org.jboss.dashboard.ui.taglib.PropertyReadTag) _005fjspx_005ftagPool_005fpanel_005fpropertyRead_0026_005fproperty_005fobject_005flocalize_005fnobody.get(org.jboss.dashboard.ui.taglib.PropertyReadTag.class);
    boolean _jspx_th_panel_005fpropertyRead_005f1_reused = false;
    try {
      _jspx_th_panel_005fpropertyRead_005f1.setPageContext(_jspx_page_context);
      _jspx_th_panel_005fpropertyRead_005f1.setParent(null);
      // /envelopes/Envelope_IFCE/full.jsp(25,87) name = localize type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_panel_005fpropertyRead_005f1.setLocalize(new java.lang.Boolean(true));
      // /envelopes/Envelope_IFCE/full.jsp(25,87) name = object type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_panel_005fpropertyRead_005f1.setObject("section");
      // /envelopes/Envelope_IFCE/full.jsp(25,87) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_panel_005fpropertyRead_005f1.setProperty("title");
      int _jspx_eval_panel_005fpropertyRead_005f1 = _jspx_th_panel_005fpropertyRead_005f1.doStartTag();
      if (_jspx_th_panel_005fpropertyRead_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpanel_005fpropertyRead_0026_005fproperty_005fobject_005flocalize_005fnobody.reuse(_jspx_th_panel_005fpropertyRead_005f1);
      _jspx_th_panel_005fpropertyRead_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_panel_005fpropertyRead_005f1, _jsp_getInstanceManager(), _jspx_th_panel_005fpropertyRead_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_mvc_005fpane_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mvc:pane
    org.jboss.dashboard.ui.taglib.PaneTag _jspx_th_mvc_005fpane_005f0 = (org.jboss.dashboard.ui.taglib.PaneTag) _005fjspx_005ftagPool_005fmvc_005fpane_0026_005fid_005fnobody.get(org.jboss.dashboard.ui.taglib.PaneTag.class);
    boolean _jspx_th_mvc_005fpane_005f0_reused = false;
    try {
      _jspx_th_mvc_005fpane_005f0.setPageContext(_jspx_page_context);
      _jspx_th_mvc_005fpane_005f0.setParent(null);
      // /envelopes/Envelope_IFCE/full.jsp(33,40) name = id type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_mvc_005fpane_005f0.setId("center");
      int _jspx_eval_mvc_005fpane_005f0 = _jspx_th_mvc_005fpane_005f0.doStartTag();
      if (_jspx_th_mvc_005fpane_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fmvc_005fpane_0026_005fid_005fnobody.reuse(_jspx_th_mvc_005fpane_005f0);
      _jspx_th_mvc_005fpane_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_mvc_005fpane_005f0, _jsp_getInstanceManager(), _jspx_th_mvc_005fpane_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_panel_005fenvelopeFooter_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  panel:envelopeFooter
    org.jboss.dashboard.ui.taglib.EnvelopeFooterTag _jspx_th_panel_005fenvelopeFooter_005f0 = (org.jboss.dashboard.ui.taglib.EnvelopeFooterTag) _005fjspx_005ftagPool_005fpanel_005fenvelopeFooter_005fnobody.get(org.jboss.dashboard.ui.taglib.EnvelopeFooterTag.class);
    boolean _jspx_th_panel_005fenvelopeFooter_005f0_reused = false;
    try {
      _jspx_th_panel_005fenvelopeFooter_005f0.setPageContext(_jspx_page_context);
      _jspx_th_panel_005fenvelopeFooter_005f0.setParent(null);
      int _jspx_eval_panel_005fenvelopeFooter_005f0 = _jspx_th_panel_005fenvelopeFooter_005f0.doStartTag();
      if (_jspx_th_panel_005fenvelopeFooter_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpanel_005fenvelopeFooter_005fnobody.reuse(_jspx_th_panel_005fenvelopeFooter_005f0);
      _jspx_th_panel_005fenvelopeFooter_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_panel_005fenvelopeFooter_005f0, _jsp_getInstanceManager(), _jspx_th_panel_005fenvelopeFooter_005f0_reused);
    }
    return false;
  }
}
