<?php
$this->headScript()
        ->prependFile($this->baseUrl('js/evento/tags.js'))
        ->prependFile($this->baseUrl('lib/select2/select2.min.js'))
        ->prependFile($this->baseUrl('js/jquery-ui-1.9.2.custom.min.js'));

$this->headLink()
        ->prependStylesheet($this->baseUrl('css/screen.css'))
        ->prependStylesheet($this->baseUrl('css/form.css'))
        ->prependStylesheet($this->baseUrl('lib/select2/select2.css'))
        ->prependStylesheet($this->baseUrl('css/jqueryui-bootstrap/jquery.ui.1.9.2.ie.css'))
        ->prependStylesheet($this->baseUrl('css/jqueryui-bootstrap/jquery-ui-1.9.2.custom.css'));
?>

<a href="<?php echo $this->url(array(), 'submissao', true) ?>"
   class="no-bottom">
   <i class="icon-reply"></i> Voltar
</a>

<br/><br/>

<h3><?php echo $this->evento['nome_tipo_evento'] ?>: <?php echo $this->evento['nome_evento'] ?></h3>

<hr/>

<fieldset>
   <div class="container">
      <div class="span-9">
         <input type="hidden" id="id_evento" value="<?php echo $this->evento['id_evento'] ?>"/>
         <i class="icon-search"></i> Buscar tag:<br/>
         <input type="text" class="text" name="termo" id="termo"
                value="" size="40" maxlength="50"
                placeholder="ex. python, ruby, java..." style="float: left;" />
         <img id="loading" src="<?php echo $this->baseUrl('img/loading.gif') ?>"
              style="display: none; float: left;" />
         <br/><br/>
         <a id="criar-tag" href="#" class="no-bottom" style="display: none;" onclick="return false;">
            <i class="icon-tag"></i> Criar tag</a>
      </div>

      <!-- lista de tags -->
      <div class="span-8">
         <i class="icon-tags"></i> Tags:<br/>
         <div class="select2-container select2-container-multi" style="width: 400px;">
            <ul class="select2-choices">
               <?php if (count($this->tags) > 0): ?>
               <?php foreach ($this->tags as $tag): ?>
               <li class="select2-search-choice" id="tag_<?php echo $tag['id'] ?>">
                  <div><?php echo $tag['descricao'] ?></div>
                  <a href="#" data-id="<?php echo $tag['id'] ?>" onclick="return false;"
                     class="select2-search-choice-close" tabindex="-1"></a>
               </li>
               <?php endforeach; ?>
               <?php else: ?>
               <div style="padding: 5px;">Nenhuma tag encontrada.</div>
               <?php endif; ?>
            </ul>
         </div>
      </div>
   </div>

</fieldset>

<div class="success" style="display: none;margin-top: 10px;"></div>
<div class="error" style="display: none;margin-top: 10px;"></div>