/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-10-09 00:03:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ResourceBundle;
import org.jboss.dashboard.LocaleManager;
import org.jboss.dashboard.ui.controller.requestChain.SessionInitializer;
import java.util.Locale;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("    <title>JBoss Dashboard Builder</title>\r\n");
      out.write("\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        * {\r\n");
      out.write("            font-family: Helvetica, Arial, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            pading: 0;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            background: repeat #55504C;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            text-shadow: #050505 0 -1px 0;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #dummy {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            border-bottom: solid 3px #777973;\r\n");
      out.write("            height: 250px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background: #FFFFFF;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #dummy2 {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            border-bottom: solid 2px #545551;\r\n");
      out.write("            height: 252px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background: transparent;\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #login-wrapper {\r\n");
      out.write("            margin: 0 0 0 -160px;\r\n");
      out.write("            width: 320px;\r\n");
      out.write("\t        text-align: left;\r\n");
      out.write("            z-index: 99;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #login-top {\r\n");
      out.write("            height: 120px;\r\n");
      out.write("            width: 201px;\r\n");
      out.write("            padding-top: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #login-content {\r\n");
      out.write("            margin-top: 120px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        label {\r\n");
      out.write("            width: 70px;\r\n");
      out.write("            float: left;\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            line-height: 14px;\r\n");
      out.write("            margin-top: -4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input.text-input {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            float: right;\r\n");
      out.write("            -moz-border-radius: 4px;\r\n");
      out.write("            -webkit-border-radius: 4px;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            border: solid 1px transparent;\r\n");
      out.write("            color: #555;\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input.button {\r\n");
      out.write("            float: right;\r\n");
      out.write("            padding: 6px 10px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            background: #E22434; /* Non CSS3 browsers. */\r\n");
      out.write("            background: linear-gradient(top, #E05A6A 0%,#E22434 100%); /* W3C */\r\n");
      out.write("            background: -webkit-gradient(linear, left top, left bottom, from(#E05A6A), to(#E22434)); /* Chrome,Safari4+ */\r\n");
      out.write("            background: -webkit-linear-gradient(top, #E05A6A 0%,#E22434 100%); /* Chrome10+,Safari5.1+ */\r\n");
      out.write("            background: -moz-linear-gradient(top,  #E05A6A,  #E22434); /* FF */\r\n");
      out.write("            background: -o-linear-gradient(top, #E05A6A 0%,#E22434 100%); /* Opera11.10+ */\r\n");
      out.write("            filter: progid:DXImageTransform.Microsoft.Gradient(endColorstr='#E22434', startColorstr='#E05A6A', gradientType='0'); /* IE6-9 */\r\n");
      out.write("            background: -ms-linear-gradient(top, #E05A6A 0%,#E22434 100%); /* IE10+ */\r\n");
      out.write("            text-shadow: #050505 0 -1px 0;\r\n");
      out.write("             background-color: #E22434;\r\n");
      out.write("            -moz-border-radius: 4px;\r\n");
      out.write("            -webkit-border-radius: 4px;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            border: solid 1px transparent;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input.button:hover {\r\n");
      out.write("            background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#a4d04a), to(#a4d04a), color-stop(80%, #76b226));\r\n");
      out.write("    \t\ttext-shadow: #050505 0 -1px 2px;\r\n");
      out.write("\t    \tbackground-color: #E22434;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        div.error {\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            background: rgba(52, 4, 0, 0.4);\r\n");
      out.write("            -moz-border-radius: 8px;\r\n");
      out.write("            -webkit-border-radius: 8px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            border: solid 1px transparent;\r\n");
      out.write("            margin: 6px 0;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"login\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"login-wrapper\" class=\"png_bg\">\r\n");
      out.write("    <div id=\"login-top\">\r\n");
      out.write("        <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/jb_logo.png\" alt=\"JBoss Logo\" title=\"Powered By JBoss\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"login-content\">\r\n");
      out.write("        ");

            LocaleManager localeManager = LocaleManager.lookup();
            Locale currentLocale =  localeManager.getCurrentLocale();
            SessionInitializer.PreferredLocale preferredLocale =  SessionInitializer.getPreferredLocale(request);
            if (preferredLocale != null) currentLocale = preferredLocale.asLocale();
            ResourceBundle i18nBundle = LocaleManager.lookup().getBundle("org.jboss.dashboard.login.messages", currentLocale);

            String messageKey = (String) request.getSession().getAttribute("login.message");
            if (messageKey == null) messageKey = "login.hint";
        
      out.write("\r\n");
      out.write("        <h3>");
      out.print( i18nBundle.getString(messageKey) );
      out.write("</h3>\r\n");
      out.write("        <form action=\"j_security_check\" method=\"POST\">\r\n");
      out.write("            <p>\r\n");
      out.write("                <label>");
      out.print( i18nBundle.getString("login.username") );
      out.write("</label>\r\n");
      out.write("                <input value=\"\" name=\"j_username\" class=\"text-input\" type=\"text\" autofocus/>\r\n");
      out.write("            </p>\r\n");
      out.write("            <br style=\"clear: both;\"/>\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("                <label>");
      out.print( i18nBundle.getString("login.password") );
      out.write("</label>\r\n");
      out.write("                <input name=\"j_password\" class=\"text-input\" type=\"password\"/>\r\n");
      out.write("            </p>\r\n");
      out.write("            <br style=\"clear: both;\"/>\r\n");
      out.write("\r\n");
      out.write("            <p>\r\n");
      out.write("                <input class=\"button\" type=\"submit\" value=\"Sign In\"/>\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"dummy\"></div>\r\n");
      out.write("<div id=\"dummy2\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
