/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-10-25 23:27:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.panels.kpi;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class edit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpanel_005fencode_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpanel_005flink_0026_005faction_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpanel_005fhidden_0026_005faction_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffactory_005fuseComponent_0026_005fbean_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fpanel_005fencode_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpanel_005flink_0026_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpanel_005fhidden_0026_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffactory_005fuseComponent_0026_005fbean_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fpanel_005fencode_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fpanel_005flink_0026_005faction_005fnobody.release();
    _005fjspx_005ftagPool_005fpanel_005fhidden_0026_005faction_005fnobody.release();
    _005fjspx_005ftagPool_005ffactory_005fuseComponent_0026_005fbean_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Submit action of the KPIEditor component-->\n");
      out.write("<form method=\"post\"  id=\"");
      if (_jspx_meth_panel_005fencode_005f0(_jspx_page_context))
        return;
      out.write("\" action=\"");
      if (_jspx_meth_panel_005flink_005f0(_jspx_page_context))
        return;
      out.write('"');
      out.write('>');
      out.write('\n');
      if (_jspx_meth_panel_005fhidden_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_factory_005fuseComponent_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</form>\n");
      out.write("<script defer=\"true\">\n");
      out.write("    setAjax(\"");
      if (_jspx_meth_panel_005fencode_005f1(_jspx_page_context))
        return;
      out.write("\");\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_panel_005fencode_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  panel:encode
    org.jboss.dashboard.ui.taglib.EncodeTag _jspx_th_panel_005fencode_005f0 = (org.jboss.dashboard.ui.taglib.EncodeTag) _005fjspx_005ftagPool_005fpanel_005fencode_0026_005fname_005fnobody.get(org.jboss.dashboard.ui.taglib.EncodeTag.class);
    boolean _jspx_th_panel_005fencode_005f0_reused = false;
    try {
      _jspx_th_panel_005fencode_005f0.setPageContext(_jspx_page_context);
      _jspx_th_panel_005fencode_005f0.setParent(null);
      // /panels/kpi/edit.jsp(24,25) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_panel_005fencode_005f0.setName("submit");
      int _jspx_eval_panel_005fencode_005f0 = _jspx_th_panel_005fencode_005f0.doStartTag();
      if (_jspx_th_panel_005fencode_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpanel_005fencode_0026_005fname_005fnobody.reuse(_jspx_th_panel_005fencode_005f0);
      _jspx_th_panel_005fencode_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_panel_005fencode_005f0, _jsp_getInstanceManager(), _jspx_th_panel_005fencode_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_panel_005flink_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  panel:link
    org.jboss.dashboard.ui.taglib.LinkTag _jspx_th_panel_005flink_005f0 = (org.jboss.dashboard.ui.taglib.LinkTag) _005fjspx_005ftagPool_005fpanel_005flink_0026_005faction_005fnobody.get(org.jboss.dashboard.ui.taglib.LinkTag.class);
    boolean _jspx_th_panel_005flink_005f0_reused = false;
    try {
      _jspx_th_panel_005flink_005f0.setPageContext(_jspx_page_context);
      _jspx_th_panel_005flink_005f0.setParent(null);
      // /panels/kpi/edit.jsp(24,64) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_panel_005flink_005f0.setAction("submit");
      int _jspx_eval_panel_005flink_005f0 = _jspx_th_panel_005flink_005f0.doStartTag();
      if (_jspx_th_panel_005flink_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpanel_005flink_0026_005faction_005fnobody.reuse(_jspx_th_panel_005flink_005f0);
      _jspx_th_panel_005flink_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_panel_005flink_005f0, _jsp_getInstanceManager(), _jspx_th_panel_005flink_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_panel_005fhidden_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  panel:hidden
    org.jboss.dashboard.ui.taglib.HiddenLinkTag _jspx_th_panel_005fhidden_005f0 = (org.jboss.dashboard.ui.taglib.HiddenLinkTag) _005fjspx_005ftagPool_005fpanel_005fhidden_0026_005faction_005fnobody.get(org.jboss.dashboard.ui.taglib.HiddenLinkTag.class);
    boolean _jspx_th_panel_005fhidden_005f0_reused = false;
    try {
      _jspx_th_panel_005fhidden_005f0.setPageContext(_jspx_page_context);
      _jspx_th_panel_005fhidden_005f0.setParent(null);
      // /panels/kpi/edit.jsp(25,0) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_panel_005fhidden_005f0.setAction("submit");
      int _jspx_eval_panel_005fhidden_005f0 = _jspx_th_panel_005fhidden_005f0.doStartTag();
      if (_jspx_th_panel_005fhidden_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpanel_005fhidden_0026_005faction_005fnobody.reuse(_jspx_th_panel_005fhidden_005f0);
      _jspx_th_panel_005fhidden_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_panel_005fhidden_005f0, _jsp_getInstanceManager(), _jspx_th_panel_005fhidden_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_factory_005fuseComponent_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  factory:useComponent
    org.jboss.dashboard.ui.taglib.factory.UseComponentTag _jspx_th_factory_005fuseComponent_005f0 = (org.jboss.dashboard.ui.taglib.factory.UseComponentTag) _005fjspx_005ftagPool_005ffactory_005fuseComponent_0026_005fbean_005fnobody.get(org.jboss.dashboard.ui.taglib.factory.UseComponentTag.class);
    boolean _jspx_th_factory_005fuseComponent_005f0_reused = false;
    try {
      _jspx_th_factory_005fuseComponent_005f0.setPageContext(_jspx_page_context);
      _jspx_th_factory_005fuseComponent_005f0.setParent(null);
      // /panels/kpi/edit.jsp(26,4) name = bean type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_factory_005fuseComponent_005f0.setBean("org.jboss.dashboard.ui.components.KPIEditor");
      int _jspx_eval_factory_005fuseComponent_005f0 = _jspx_th_factory_005fuseComponent_005f0.doStartTag();
      if (_jspx_th_factory_005fuseComponent_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffactory_005fuseComponent_0026_005fbean_005fnobody.reuse(_jspx_th_factory_005fuseComponent_005f0);
      _jspx_th_factory_005fuseComponent_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_factory_005fuseComponent_005f0, _jsp_getInstanceManager(), _jspx_th_factory_005fuseComponent_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_panel_005fencode_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  panel:encode
    org.jboss.dashboard.ui.taglib.EncodeTag _jspx_th_panel_005fencode_005f1 = (org.jboss.dashboard.ui.taglib.EncodeTag) _005fjspx_005ftagPool_005fpanel_005fencode_0026_005fname_005fnobody.get(org.jboss.dashboard.ui.taglib.EncodeTag.class);
    boolean _jspx_th_panel_005fencode_005f1_reused = false;
    try {
      _jspx_th_panel_005fencode_005f1.setPageContext(_jspx_page_context);
      _jspx_th_panel_005fencode_005f1.setParent(null);
      // /panels/kpi/edit.jsp(29,13) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_panel_005fencode_005f1.setName("submit");
      int _jspx_eval_panel_005fencode_005f1 = _jspx_th_panel_005fencode_005f1.doStartTag();
      if (_jspx_th_panel_005fencode_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpanel_005fencode_0026_005fname_005fnobody.reuse(_jspx_th_panel_005fencode_005f1);
      _jspx_th_panel_005fencode_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_panel_005fencode_005f1, _jsp_getInstanceManager(), _jspx_th_panel_005fencode_005f1_reused);
    }
    return false;
  }
}
